### ISSUE TITLE
接您汉化的作者链接失效联系不上了，您有他继续汉化的资源吗？

### ISSUE THREAD

**Issue by Huaweidev** [jiangfangzheng/RDCMan-zh_CN#1]
接您汉化的作者链接失效联系不上了，您有他继续汉化的资源吗？能否上传？
https://www.52pojie.cn/thread-993959-1-1.html

**Comment by jiangfangzheng** [comment]
> 接您汉化的作者链接失效联系不上了，您有他继续汉化的资源吗？能否上传？ https://www.52pojie.cn/thread-993959-1-1.html

https://www.lanzout.com/i53lwbc    密码:4i6v
