### ISSUE TITLE
最新版为2.9.3,希望再折腾下

### ISSUE THREAD

**Issue by uranus829** [jiangfangzheng/RDCMan-zh_CN#2]
最新版为2.9.3,希望再折腾下

**Comment by poppy7921** [comment]
吾爱上已经有人汉化了，汉化工具是dnSpy v6.1.9
帖子地址：https://www.52pojie.cn/thread-1823954-1-1.html
文件地址：https://ssdl.lanzouc.com/iXh6Z1683fze

**Comment by poppy7921** [comment]
上传一个
[RDCMan2.93chs.zip](https://github.com/jiangfangzheng/RDCMan-zh_CN/files/13455402/RDCMan2.93chs.zip)

**Comment by jiangfangzheng** [comment]
再次感谢 @poppy7921 ^_^
